parameters:
    fsv_typography.typograph.class: Fsv\TypographyBundle\Typograph\MdashTypograph
    fsv_typography.textarea_type_extension.class: Fsv\TypographyBundle\Form\Extension\TextareaTypeExtension

services:
    fsv_typography.typograph:
        class: "%fsv_typography.typograph.class%"
        calls:
            - [setup, ["%fsv_typography.typograph.options%"]]
