language: php

php:
    - 5.5
    - 5.6
    - 7.0
    - hhvm

sudo: false

env:
    - SYMFONY_VERSION="2.7.*"
    - SYMFONY_VERSION="2.8.*"
    - SYMFONY_VERSION="3.0.*"

before_install:
    - composer self-update

install:
    - composer require symfony/symfony:${SYMFONY_VERSION} --no-update
    - composer update --prefer-dist --no-interaction
